<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Giày chanel',
                'description' => 'Giày chanel',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 1,
                'image' => 'storage/product/chanel/shoe.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo khoác Chanel',
                'description' => 'Áo khoác chanel',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 1,
                'image' => 'storage/product/chanel/aokhoac.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách chanel',
                'description' => 'Túi xách chanel',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 1,
                'image' => 'storage/product/chanel/bag.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Chanel #2',
                'description' => 'Giày chanel',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 1,
                'image' => 'storage/product/chanel/shoe2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Gucci',
                'description' => 'Áo Gucci',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 2,
                'image' => 'storage/product/gucci/aogucci.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Gucci',
                'description' => 'Quần Gucci',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 2,
                'brand_id' => 2,
                'image' => 'storage/product/gucci/quan.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Gucci',
                'description' => 'Giày Gucci',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 2,
                'image' => 'storage/product/gucci/shoe1.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Gucci',
                'description' => 'Túi xách Gucci',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 2,
                'image' => 'storage/product/gucci/bag1.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Gucci #2',
                'description' => 'Túi xách Gucci',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 2,
                'image' => 'storage/product/gucci/bag2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Gucci',
                'description' => 'Giày Gucci',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 2,
                'image' => 'storage/product/gucci/shoe2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Hermes',
                'description' => 'Áo Hermes',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 3,
                'image' => 'storage/product/hermes/ao.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Hermes',
                'description' => 'Quần Hermes',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 2,
                'brand_id' => 3,
                'image' => 'storage/product/hermes/quan.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Hermes',
                'description' => 'Giày Hermes',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 3,
                'image' => 'storage/product/hermes/shoe.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Hermes',
                'description' => 'Túi xách Hermes',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 3,
                'image' => 'storage/product/hermes/bag.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Hermes #2',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 3,
                'image' => 'storage/product/hermes/ao2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Hermes #2',
                'description' => 'Quần Hermes',
                'price' => 299000,
                'category_id' => 2,
                'brand_id' => 3,
                'image' => 'storage/product/hermes/quan2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Dior',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 4,
                'image' => 'storage/product/dior/ao.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Dior',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 2,
                'brand_id' => 4,
                'image' => 'storage/product/dior/quan.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Dior',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 4,
                'image' => 'storage/product/dior/shoe.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Dior',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 4,
                'image' => 'storage/product/dior/bag.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Dior #2',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 4,
                'image' => 'storage/product/dior/bag2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Dior #2',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 4,
                'image' => 'storage/product/dior/ao2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Adidas',
                'description' => 'Áo Adidas',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 5,
                'image' => 'storage/product/adidas/ao.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Adidas',
                'description' => 'Quần Adidas',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 2,
                'brand_id' => 5,
                'image' => 'storage/product/adidas/quan.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Adidas',
                'description' => 'Giày Adidas',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 5,
                'image' => 'storage/product/adidas/shoe.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Adidas',
                'description' => 'Túi xách Adidas',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 5,
                'image' => 'storage/product/adidas/bag.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Adidas #2',
                'description' => 'Quần Adidas',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 2,
                'brand_id' => 5,
                'image' => 'storage/product/adidas/quan2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Adidas #2',
                'description' => 'Giày Adidas',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 5,
                'image' => 'storage/product/adidas/shoe2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Nike',
                'description' => 'Áo Nike',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 6,
                'image' => 'storage/product/nike/ao.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Nike',
                'description' => 'Quần nike',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 2,
                'brand_id' => 6,
                'image' => 'storage/product/nike/quan.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Nike',
                'description' => 'Giày Nike',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 6,
                'image' => 'storage/product/nike/shoe.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Nike',
                'description' => 'Túi xách Nike',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 6,
                'image' => 'storage/product/nike/bag.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Nike #2',
                'description' => 'Giày Nike',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 6,
                'image' => 'storage/product/nike/shoe2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Nike #2',
                'description' => '',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 6,
                'image' => 'storage/product/nike/ao2.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Áo Zara',
                'description' => 'Áo Zara',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 1,
                'brand_id' => 7,
                'image' => 'storage/product/zara/zara.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Quần Zara',
                'description' => 'Quần Zara',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 2,
                'brand_id' => 7,
                'image' => 'storage/product/zara/quan.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Giày Zara',
                'description' => 'Giày Zara',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 3,
                'brand_id' => 7,
                'image' => 'storage/product/zara/shoe.jpg',
                'views' => rand(1000, 5000),
            ],
            [
                'name' => 'Túi xách Zara',
                'description' => 'Túi xách Zara',
                'price' => rand(100, 1000) * 1000,
                'category_id' => 4,
                'brand_id' => 7,
                'image' => 'storage/product/zara/bag.jpg',
                'views' => rand(1000, 5000),
            ],

        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
